<template>
    <div>
        <form class="form" v-on:submit.prevent="handleForm">
            <h2>Create an account</h2>
            <p>Already have an account? <a href="/login">Sign in</a></p>

            <div class="form-group">
                <label for="name">UMKM's Name</label>
                <p class="error-form" v-if="errors.name" >{{errors.name[0]}}</p>
                <input type="text" v-model="form.name" id="name"/>
            </div>
            <div class="section">
                <div class="form-group">
                    <label for="place">Place</label>
                    <p class="error-form" v-if="errors.place" >{{errors.place[0]}}</p>
                    <input type="text" v-model="form.place" id="place"/>
                </div>
                <div class="space"></div>
                    <div class="form-group">
                        <label for="phone">Phone Number (WhatsApp)</label>
                        <p class="error-form" v-if="errors.wa" >{{errors.wa[0]}}</p>
                        <input type="text"  v-model="form.wa" id="phone"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <p class="error-form" v-if="errors.email" >{{errors.email[0]}}</p>
                    <input type="email" v-model="form.email" id="email"/>
                </div>
                <div class="form-group">
                    <label for="instagram">Instagram</label>
                    <p class="error-form" v-if="errors.ig" >{{errors.ig[0]}}</p>
                    <input type="text" v-model="form.ig" id="instagram"/>
                </div>
                        
                <button class="button" type="submit">Sign Up
                    <svg v-if="loading" class="loading" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="background: none; display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                        <g>
                        <path d="M50 15A35 35 0 1 0 74.74873734152916 25.251262658470843" fill="none" stroke="#ffffff" stroke-width="12"></path>
                        <path d="M49 3L49 27L61 15L49 3" fill="#ffffff"></path>
                        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
                        </g>
                        <!-- [ldio] generated by https://loading.io/ -->
                    </svg>
                </button>

            <div class="backgroud"></div>
            <div class="clear"></div>
        </form>
        <div class="registration-success hidePopup">
            <div class="popup-header">
                <h2>Registrasi Berhasil !</h2>
            </div>
            <div class="popup-body">
                Mohon cek secara berkala email yang anda daftarkan untuk menerima 
                akses login dari kami jika anda lolos seleksi administrasi.
            </div>
            <a class="button popup-button" @click.prevent="hidePopup">Mengerti</a>
        </div>
    </div>
    
</template>

<script>
export default {
    async mounted(){
        // try{
        //     await axios.post('/api/register',{halo:"haiii",coba:"dulu"}).then(response=>{
        //         console.log(response);
        //     })
        // }catch(e){
        //     console.log(e)
        // }
        console.log('halo')
    },
    data(){
        return{
            errors:'',
            loading:false,
            form:{
                name : '',
                place:'',
                wa:'',
                email:'',
                ig:'',
            }
        }
    },
    methods:{
        async handleForm(){
            // console.log(this.form);
            try{
                this.loading=true;
                await axios.post('/api/register',this.form).then(response=>{
                    console.log(response.data);
                    this.errors='';

                    let registrationPopup = document.getElementsByClassName('registration-success')[0];
                    registrationPopup.classList.add('showPopup');
                    registrationPopup.classList.remove('hidePopup');

                    this.loading = false;
                })
            }catch(e){
                this.errors = e.response.data.errors;
                console.log(e.response)
            }
        },
        hidePopup(){
            let registrationPopup = document.getElementsByClassName('registration-success')[0];
            registrationPopup.classList.remove('showPopup');
            registrationPopup.classList.add('hidePopup');
        }
    }
}
</script>

<style>
    .error-form{
        display: block;
        color: red;
        margin: 0;
        padding: 0;
    }
    button.button .loading{
        width: 21px;
        height: 21px;
        float:right;
        margin-left: 10px;
    }
    .registration-success{
        position: fixed;
        top: 50%;
        left:50%;
        transform:translate(-50%,-50%); 
        width: 30%;
        background: grey;
        padding: 20px;
        border-radius: 20px;
    }
    .hidePopup{
        display: none;
    }
    .showPopup{
        z-index: 2;
        opacity:1;
        animation: showPopup 0.3s;
    }
    @keyframes showPopup {
        0%{
            transform: translateX(-50%);
            top: -50%;
            left: 50%;
            display: none;
        }
    }
    .popup-header{
        margin-bottom: 10px;
        font-size: 30px;
    }
    .popup-header h2{
        margin: 25px 0px;
    }
    .popup-body{
        text-align: justify;
    }
    a.popup-button{
        font-size: 15px;
        padding: 7px 15px;
        border-radius: 10px;
        margin-top: 20px;
        float: right;
    }
</style>