<template>
    <div>
        <form class="form" v-on:submit.prevent="handleForm">
            <h2 style="color:#007bff;margin-bottom:15px;">Join With US</h2>

            <div class="form-group">
                <label for="name">UMKM's Name</label>
                <p class="error-form" v-if="errors.name" >{{errors.name[0]}}</p>
                <input type="text" v-model="form.name" id="name"/>
            </div>
            <div class="section">
                <div class="form-group">
                    <label for="place">Place</label>
                    <p class="error-form" v-if="errors.place" >{{errors.place[0]}}</p>
                    <input type="text" v-model="form.place" id="place"/>
                </div>
                <div class="space"></div>
                    <div class="form-group">
                        <label for="phone">Phone Number (WhatsApp)</label>
                        <p class="error-form" v-if="errors.wa" >{{errors.wa[0]}}</p>
                        <input type="text"  v-model="form.wa" id="phone"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <p class="error-form" v-if="errors.email" >{{errors.email[0]}}</p>
                    <input type="email" v-model="form.email" id="email"/>
                </div>
                <div class="form-group">
                    <label for="instagram">Instagram</label>
                    <p class="error-form" v-if="errors.ig" >{{errors.ig[0]}}</p>
                    <input type="text" v-model="form.ig" id="instagram"/>
                </div>
                        
                <button class="button" type="submit">Join
                    <svg v-if="loading" class="loading" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="background: none; display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                        <g>
                        <path d="M50 15A35 35 0 1 0 74.74873734152916 25.251262658470843" fill="none" stroke="#ffffff" stroke-width="12"></path>
                        <path d="M49 3L49 27L61 15L49 3" fill="#ffffff"></path>
                        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
                        </g>
                        <!-- [ldio] generated by https://loading.io/ -->
                    </svg>
                </button>

            <div class="backgroud"></div>
            <div class="clear"></div>
        </form>
        <div class="background-popup">
        </div>
        <div class="registration-success hidePopup">
            <img src="img/success.png" id="success" width="50px" height="50px">
            <div class="popup-header">
                <h2>Registrasi Berhasil</h2>
            </div>
            <div class="popup-body">
                <span>
                    Mohon cek secara berkala email yang anda daftarkan untuk menerima 
                    akses login dari kami jika anda lolos seleksi administrasi.
                </span>
                <a class="button popup-button" @click.prevent="hidePopup">Ok</a>
            </div>
        </div>
    </div>
    
</template>

<script>
export default {
    data(){
        return{
            errors:'',
            loading:false,
            form:{
                name : '',
                place:'',
                wa:'',
                email:'',
                ig:'',
            }
        }
    },
    methods:{
        async handleForm(){
            // console.log(this.form);
            try{
                this.loading=true;
                await axios.post('/api/register',this.form).then(response=>{
                    this.errors='';

                    // change background to grey
                    let backgroudPopup = document.getElementsByClassName('background-popup')[0];
                    backgroudPopup.style.backgroundColor = '#737373';
                    backgroudPopup.style.zIndex = '2';

                    // show popup
                    let registrationPopup = document.getElementsByClassName('registration-success')[0];
                    registrationPopup.classList.add('showPopup');
                    registrationPopup.classList.remove('hidePopup');

                    this.form = {
                        name : '',
                        place:'',
                        wa:'',
                        email:'',
                        ig:'',
                    }
                    this.loading = false;

                    setTimeout(function(){
                        document.getElementById('success').classList.add('success');
                    },500)
                })
            }catch(e){
                this.errors = e.response.data.errors;
                this.loading = false;
            }
        },
        hidePopup(){
            let registrationPopup = document.getElementsByClassName('registration-success')[0];
            registrationPopup.classList.remove('showPopup');
            registrationPopup.classList.add('hidePopup');

            let backgroudPopup = document.getElementsByClassName('background-popup')[0];
            backgroudPopup.style.backgroundColor = 'transparent';
            backgroudPopup.style.zIndex = '-1';

            document.getElementById('success').classList.remove('success');
        }
    }
}
</script>

<style>
    .error-form{
        display: block;
        color: red;
        margin: 0;
        padding: 0;
    }
    button.button .loading{
        width: 21px;
        height: 21px;
        float:right;
        margin-left: 10px;
    }
    .background-popup{
        display:block;
        width:100%;
        height:100vh;
        z-index:-1;
        background:transparent;
        opacity: 0.4;
        position: fixed;
        top: 0;
        left:0;
    }
    .registration-success{
        position: fixed;
        top: 50%;
        left:50%;
        transform:translate(-50%,-50%); 
        width: 25%;
        background: white;
        padding: 0px;
        border-radius: 10px;
    }
    .main .register .registration-success img{
        display: none;
        width: 80px;
        height: 80px;
        position: absolute;
        left: 50%;
        top:0px;
        transform: translate(-50%,-50%);
    }
    .main .register .registration-success img.success{
        display: block;
        animation: ceklis 0.7s;
    }
    @keyframes ceklis{
        0%{
            width: 150px;
            height: 150px;
        }
    }
    .hidePopup{
        display: none;
    }
    .showPopup{
        z-index: 3;
        opacity:1;
        animation: showPopup 0.3s;
    }
    @keyframes showPopup {
        0%{
            transform: translateX(-50%);
            top: -50%;
            left: 50%;
            display: none;
        }
    }
    .popup-header{
        margin-top: 50px;
        margin-bottom: 20px;
        text-align: center;
        font-size: 20px;
    }
    .popup-header h2{
        margin: 0;
    }
    .popup-body{
        text-align: justify;
        padding: 0 20px 20px 20px;
        display: flex;
        flex-direction: column;
    }
    a.popup-button{
        text-align: center;
        font-size: 15px;
        padding: 7px 15px;
        border-radius: 5px;
        margin-top: 25px;
        position: relative;
    }
</style>